name: .NET Core (win-x64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --logger:"console;verbosity=normal"
    - name: Publish
      run: dotnet publish AllMyLights/AllMyLights.csproj --runtime win-x64 --configuration Release -p:PublishSingleFile=true -p:UseAppHost=true --self-contained false
    - name: Archive
      shell: bash
      run: |
        cp allmylightsrc.json AllMyLights\bin\Release\netcoreapp3.1\win-x64\publish\allmylightsrc.json
        7z a -tzip "target-win-x64.zip" "./AllMyLights/bin/Release/netcoreapp3.1/win-x64/publish/*"
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: target-win-x64
        path: target-win-x64.zip