name: test

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ main ]
 
jobs:
  test:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --logger:"console;verbosity=normal"